# name: Django CI

name: Django App Test

on:
  push:
    paths:
      - "**content/**"
      - ".github/workflows/django.yml"
    branches:
      - main
      - "*_communal_the_test"
  pull_request:
    branches:
      - main

jobs:
  test-django:
    runs-on: ubuntu-latest

    steps:
      # リポジトリチェックアウト
      - uses: actions/checkout@v3

      # Python セットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Django インストール
      - name: Install Django
        run: pip install django

      # 依存シェルスクリプトでアプリ起動
      - name: Start Django App
        run: |
          cd content/t_kyn_test_app
          chmod +x ./all_manage_t_kyn_deploy.sh ./django_preinstall.sh
          ./django_preinstall.sh
          echo "=====view the app help====="
          python manage_t_kyn.py
          echo "=====run the app server====="
          nohup python manage_t_kyn.py runserver 127.0.0.1:18000 > /dev/null 2>&1 &
          echo "Waiting for server to start..."
          echo "=====ps aux====="
          ps aux | grep manage_t_kyn.py
          # echo "=====netstat====="
          # netstat -an | grep 18000
          echo "=====sleep 20 seconds====="
          sleep 20
          echo "=====curl test====="
          curl -kv http://127.0.0.1:18000/myapp
          echo "=====curl admin test====="
          curl -kv http://127.0.0.1:18000/admin/login/?next=/admin/
          echo "=====sleep 10 seconds====="
          sleep 10  # サーバ起動待機

