# name: Django CI

name: Django App Test

on:
  push:
    paths:
      - "**content/**"
      - ".github/workflows/django.yml"
    branches:
      - main
      - "*_communal_the_test"
  pull_request:
    branches:
      - main

jobs:
  test-django:
    runs-on: ubuntu-latest

    steps:
      # リポジトリチェックアウト
      - uses: actions/checkout@v3

      # Python セットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Django インストール
      - name: Install Django
        run: pip install django

      # 依存シェルスクリプトでアプリ起動
      - name: Start Django App
        run: |
          cd content/t_kyn_test_app
          chmod +x ./all_manage_t_kyn_deploy.sh ./django_preinstall.sh
          ./django_preinstall.sh
          echo "=====view the app help====="
          python manage_t_kyn.py
          echo "=====run the app server====="
          nohup python manage_t_kyn.py runserver > /dev/null 2>&1 &
          echo "Waiting for server to start..."
          echo "=====ps aux====="
          ps aux | grep manage_t_kyn.py
          echo "=====netstat====="
          netstat -an | grep 8000
          echo "=====sleep 20 seconds====="
          sleep 20
          echo "=====curl test====="
          curl -kv http://localhost:8000/myapp
          echo "=====curl admin test====="
          curl -kv http://localhost:8000/admin/login/?next=/admin/
          echo "=====sleep 10 seconds====="
          sleep 10  # サーバ起動待機

      # # curl でアクセス確認
      # - name: Test MyApp
      #   run: |
      #     curl -kv http://localhost:8000/myapp


# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.7, 3.8, 3.9]

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
#     - name: curl Tests
#       run: |
#         curl http://localhost:8080/
