# name: Django CI

name: Django App Test

on:
  push:
    paths:
      - "**content/**"
      - ".github/workflows/django.yml"
    branches:
      - main
      - "*_communal_the_test"
  pull_request:
    branches:
      - main

jobs:
  test-django:
    runs-on: ubuntu-latest

    steps:
      # リポジトリチェックアウト
      - uses: actions/checkout@v3

      # Python セットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Django And Pillowインストール
      - name: Install Django And Pillow
        run: |
          pip install django
          pip install Pillow

      # 依存シェルスクリプトでアプリ起動
      - name: Start Django App
        run: |
          cd content/t_kyn_test_app
          chmod +x ./all_manage_t_kyn_deploy.sh ./django_preinstall.sh
          ./django_preinstall.sh
          echo "=====view the app help====="
          python manage_t_kyn.py
          echo "=====run the app server====="
          nohup python manage_t_kyn.py runserver 127.0.0.1:18000 > django-server.log 2>&1 &
          echo "Waiting for server to start..."
          echo "=====ps aux====="
          ps aux | grep manage_t_kyn.py
          echo "=====sleep 5 seconds====="
          sleep 5
          echo "===== DUMPING SERVER LOG ====="
          # ログファイルの中身をCIのログに出力して確認する！
          cat django-server.log
          echo "=====ps aux====="
          ps aux | grep manage_t_kyn.py
          echo "=====curl test====="
          curl -kv http://127.0.0.1:18000/myapp
          echo "=====curl admin test====="
          curl -kv http://127.0.0.1:18000/admin/login/?next=/admin/


      # 依存シェルスクリプトでアプリ起動
      - name: curl another test
        run: |
          echo "=====curl test====="
          curl -kv http://127.0.0.1:18000/album/
          echo "=====curl admin test====="
          curl -kv http://localhost:8000/chat/
          echo "=====curl todolist test====="
          curl -kv http://localhost:8000/todolist/
          echo "=====curl location test====="
          curl -kv http://localhost:8000/location/
